/* Generated by GOB (v2.0.14)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>


#include <gtk/gtk.h>

#ifndef __MN_BLINKING_IMAGE_H__
#define __MN_BLINKING_IMAGE_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define MN_TYPE_BLINKING_IMAGE	(mn_blinking_image_get_type())
#define MN_BLINKING_IMAGE(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), mn_blinking_image_get_type(), MNBlinkingImage)
#define MN_BLINKING_IMAGE_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), mn_blinking_image_get_type(), MNBlinkingImage const)
#define MN_BLINKING_IMAGE_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), mn_blinking_image_get_type(), MNBlinkingImageClass)
#define MN_IS_BLINKING_IMAGE(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), mn_blinking_image_get_type ())

#define MN_BLINKING_IMAGE_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), mn_blinking_image_get_type(), MNBlinkingImageClass)

/* Private structure type */
typedef struct _MNBlinkingImagePrivate MNBlinkingImagePrivate;

/*
 * Main object structure
 */
#ifndef __TYPEDEF_MN_BLINKING_IMAGE__
#define __TYPEDEF_MN_BLINKING_IMAGE__
typedef struct _MNBlinkingImage MNBlinkingImage;
#endif
struct _MNBlinkingImage {
	GtkImage __parent__;
	/*< private >*/
	MNBlinkingImagePrivate *_priv;
};

/*
 * Class definition
 */
typedef struct _MNBlinkingImageClass MNBlinkingImageClass;
struct _MNBlinkingImageClass {
	GtkImageClass __parent__;
};


/*
 * Public methods
 */
GType	mn_blinking_image_get_type	(void);
gboolean 	mn_blinking_image_get_blinking	(MNBlinkingImage * self);
void 	mn_blinking_image_set_blinking	(MNBlinkingImage * self,
					gboolean val);
GtkWidget * 	mn_blinking_image_new	(void);
void 	mn_blinking_image_set_from_stock	(MNBlinkingImage * self,
					const char * stock_id,
					GtkIconSize icon_size);

/*
 * Argument wrapping macros
 */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define MN_BLINKING_IMAGE_PROP_BLINKING(arg)    	"blinking", __extension__ ({gboolean z = (arg); z;})
#define MN_BLINKING_IMAGE_GET_PROP_BLINKING(arg)	"blinking", __extension__ ({gboolean *z = (arg); z;})
#else /* __GNUC__ && !__STRICT_ANSI__ */
#define MN_BLINKING_IMAGE_PROP_BLINKING(arg)    	"blinking",(gboolean )(arg)
#define MN_BLINKING_IMAGE_GET_PROP_BLINKING(arg)	"blinking",(gboolean *)(arg)
#endif /* __GNUC__ && !__STRICT_ANSI__ */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
