/* Generated by GOB (v2.0.12)   (do not edit directly) */

#ifndef __MN_CORBA_OBJECT_PRIVATE_H__
#define __MN_CORBA_OBJECT_PRIVATE_H__

#include "mn-corba-object.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _MNCORBAObjectPrivate {
#line 31 "mn-corba-object.gob"
	CORBA_Object object;
#line 52 "mn-corba-object.gob"
	char * iid;
#line 55 "mn-corba-object.gob"
	unsigned int monitor_id;
#line 20 "mn-corba-object-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
