/* Generated by GOB (v2.0.9)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>


#include "mn-mailbox.h"

#ifndef __MN_IMAP_MAILBOX_H__
#define __MN_IMAP_MAILBOX_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define MN_TYPE_IMAP_MAILBOX	(mn_imap_mailbox_get_type())
#define MN_IMAP_MAILBOX(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), mn_imap_mailbox_get_type(), MNIMAPMailbox)
#define MN_IMAP_MAILBOX_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), mn_imap_mailbox_get_type(), MNIMAPMailbox const)
#define MN_IMAP_MAILBOX_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), mn_imap_mailbox_get_type(), MNIMAPMailboxClass)
#define MN_IS_IMAP_MAILBOX(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), mn_imap_mailbox_get_type ())

#define MN_IMAP_MAILBOX_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), mn_imap_mailbox_get_type(), MNIMAPMailboxClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_MN_IMAP_MAILBOX__
#define __TYPEDEF_MN_IMAP_MAILBOX__
typedef struct _MNIMAPMailbox MNIMAPMailbox;
#endif
struct _MNIMAPMailbox {
	MNMailbox __parent__;
};

/*
 * Class definition
 */
typedef struct _MNIMAPMailboxClass MNIMAPMailboxClass;
struct _MNIMAPMailboxClass {
	MNMailboxClass __parent__;
};


/*
 * Public methods
 */
GType	mn_imap_mailbox_get_type	(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
