/* Generated by GOB (v2.0.10)   (do not edit directly) */

#ifndef __MN_MAILBOXES_PRIVATE_H__
#define __MN_MAILBOXES_PRIVATE_H__

#include "mn-mailboxes.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _MNMailboxesPrivate {
#line 36 "mn-mailboxes.gob"
	GSList * list;
#line 37 "mn-mailboxes.gob"
	unsigned int timeout_id;
#line 38 "mn-mailboxes.gob"
	unsigned int delay_notification_id;
#line 39 "mn-mailboxes.gob"
	unsigned int mailboxes_notification_id;
#line 22 "mn-mailboxes-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
