/* Generated by GOB (v2.0.12) on Tue Aug  9 22:01:57 2005
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 12

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "mn-mailbox-properties-dialog.h"

#include "mn-mailbox-properties-dialog-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 26 "mn-mailbox-properties-dialog.gob"

#include "config.h"
#include <glib/gi18n.h>
#include "mn-mailbox-properties.h"
#include "mn-autodetect-mailbox-properties.h"
#if defined(WITH_MBOX) || defined(WITH_MH) || defined(WITH_MAILDIR) || defined(WITH_SYLPHEED)
#include "mn-system-vfs-mailbox-properties.h"
#endif
#ifdef WITH_POP3
#include "mn-pop3-mailbox-properties.h"
#endif
#ifdef WITH_IMAP
#include "mn-imap-mailbox-properties.h"
#endif
#ifdef WITH_GMAIL
#include "mn-gmail-mailbox-properties.h"
#endif
#ifdef WITH_EVOLUTION
#include "mn-evolution-mailbox-properties.h"
#endif
#include "mn-util.h"
#include "mn-mailboxes.h"
#include "mn-shell.h"

enum {
  COLUMN_PROPERTIES,
  COLUMN_STOCK_ID,
  COLUMN_LABEL,
  N_COLUMNS
};

static GType selected_type = 0;

#line 61 "mn-mailbox-properties-dialog.c"
/* self casting macros */
#define SELF(x) MN_MAILBOX_PROPERTIES_DIALOG(x)
#define SELF_CONST(x) MN_MAILBOX_PROPERTIES_DIALOG_CONST(x)
#define IS_SELF(x) MN_IS_MAILBOX_PROPERTIES_DIALOG(x)
#define TYPE_SELF MN_TYPE_MAILBOX_PROPERTIES_DIALOG
#define SELF_CLASS(x) MN_MAILBOX_PROPERTIES_DIALOG_CLASS(x)

#define SELF_GET_CLASS(x) MN_MAILBOX_PROPERTIES_DIALOG_GET_CLASS(x)

/* self typedefs */
typedef MNMailboxPropertiesDialog Self;
typedef MNMailboxPropertiesDialogClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void mn_mailbox_properties_dialog_init (MNMailboxPropertiesDialog * o) G_GNUC_UNUSED;
static void mn_mailbox_properties_dialog_class_init (MNMailboxPropertiesDialogClass * c) G_GNUC_UNUSED;
static GObject * ___3_mn_mailbox_properties_dialog_constructor (GType type, unsigned int n_construct_properties, GObjectConstructParam * construct_params) G_GNUC_UNUSED;
static void mn_mailbox_properties_dialog_add_type (MNMailboxPropertiesDialog * self, GType type) G_GNUC_UNUSED;
static void mn_mailbox_properties_dialog_set_active_properties (MNMailboxPropertiesDialog * self, MNMailboxProperties * properties) G_GNUC_UNUSED;
static MNMailboxProperties * mn_mailbox_properties_dialog_get_active_properties (MNMailboxPropertiesDialog * self) G_GNUC_UNUSED;
static MNMailboxProperties * mn_mailbox_properties_dialog_get_properties_by_type (MNMailboxPropertiesDialog * self, const char * type) G_GNUC_UNUSED;
static MNMailboxProperties * mn_mailbox_properties_dialog_get_properties_by_g_type (MNMailboxPropertiesDialog * self, GType type) G_GNUC_UNUSED;
static void mn_mailbox_properties_dialog_update_complete (MNMailboxPropertiesDialog * self) G_GNUC_UNUSED;
static void mn_mailbox_properties_dialog_update_default_name (MNMailboxPropertiesDialog * self) G_GNUC_UNUSED;

enum {
	PROP_0,
	PROP_DIALOG_PARENT,
	PROP_MAILBOX
};

/* pointer to the class of our parent */
static MNDialogClass *parent_class = NULL;

/* Short form macros */
#define self_get_mailbox mn_mailbox_properties_dialog_get_mailbox
#define self_set_mailbox mn_mailbox_properties_dialog_set_mailbox
#define self_add_type mn_mailbox_properties_dialog_add_type
#define self_set_active_properties mn_mailbox_properties_dialog_set_active_properties
#define self_get_active_properties mn_mailbox_properties_dialog_get_active_properties
#define self_get_properties_by_type mn_mailbox_properties_dialog_get_properties_by_type
#define self_get_properties_by_g_type mn_mailbox_properties_dialog_get_properties_by_g_type
#define self_get_current_mailbox mn_mailbox_properties_dialog_get_current_mailbox
#define self_apply mn_mailbox_properties_dialog_apply
#define self_update_complete mn_mailbox_properties_dialog_update_complete
#define self_update_default_name mn_mailbox_properties_dialog_update_default_name
#define self_new mn_mailbox_properties_dialog_new
#define self_type_changed_h mn_mailbox_properties_dialog_type_changed_h
#define self_name_changed_h mn_mailbox_properties_dialog_name_changed_h
#define self_name_default_button_clicked_h mn_mailbox_properties_dialog_name_default_button_clicked_h
#define self_entry_activate_h mn_mailbox_properties_dialog_entry_activate_h
GType
mn_mailbox_properties_dialog_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (MNMailboxPropertiesDialogClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) mn_mailbox_properties_dialog_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (MNMailboxPropertiesDialog),
			0 /* n_preallocs */,
			(GInstanceInitFunc) mn_mailbox_properties_dialog_init,
			NULL
		};

		type = g_type_register_static (MN_TYPE_DIALOG, "MNMailboxPropertiesDialog", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((MNMailboxPropertiesDialog *)g_object_new(mn_mailbox_properties_dialog_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static MNMailboxPropertiesDialog * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static MNMailboxPropertiesDialog *
GET_NEW_VARG (const char *first, ...)
{
	MNMailboxPropertiesDialog *ret;
	va_list ap;
	va_start (ap, first);
	ret = (MNMailboxPropertiesDialog *)g_object_new_valist (mn_mailbox_properties_dialog_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___dispose (GObject *obj_self)
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::dispose"
	MNMailboxPropertiesDialog *self G_GNUC_UNUSED = MN_MAILBOX_PROPERTIES_DIALOG (obj_self);
	if (G_OBJECT_CLASS (parent_class)->dispose) \
		(* G_OBJECT_CLASS (parent_class)->dispose) (obj_self);
#line 66 "mn-mailbox-properties-dialog.gob"
	if(self->_priv->mailbox) { g_object_unref ((gpointer) self->_priv->mailbox); self->_priv->mailbox = NULL; }
#line 167 "mn-mailbox-properties-dialog.c"
#line 110 "mn-mailbox-properties-dialog.gob"
	if(self->_priv->store) { g_object_unref ((gpointer) self->_priv->store); self->_priv->store = NULL; }
#line 170 "mn-mailbox-properties-dialog.c"
}
#undef __GOB_FUNCTION__


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::finalize"
	MNMailboxPropertiesDialog *self G_GNUC_UNUSED = MN_MAILBOX_PROPERTIES_DIALOG (obj_self);
	gpointer priv G_GNUC_UNUSED = self->_priv;
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 112 "mn-mailbox-properties-dialog.gob"
	if(self->_priv->default_name) { g_free ((gpointer) self->_priv->default_name); self->_priv->default_name = NULL; }
#line 185 "mn-mailbox-properties-dialog.c"
}
#undef __GOB_FUNCTION__

static void 
mn_mailbox_properties_dialog_init (MNMailboxPropertiesDialog * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::init"
	o->_priv = G_TYPE_INSTANCE_GET_PRIVATE(o,MN_TYPE_MAILBOX_PROPERTIES_DIALOG,MNMailboxPropertiesDialogPrivate);
}
#undef __GOB_FUNCTION__
static void 
mn_mailbox_properties_dialog_class_init (MNMailboxPropertiesDialogClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	g_type_class_add_private(c,sizeof(MNMailboxPropertiesDialogPrivate));

	parent_class = g_type_class_ref (MN_TYPE_DIALOG);

#line 115 "mn-mailbox-properties-dialog.gob"
	g_object_class->constructor = ___3_mn_mailbox_properties_dialog_constructor;
#line 208 "mn-mailbox-properties-dialog.c"
	g_object_class->dispose = ___dispose;
	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_pointer
		("dialog_parent" /* name */,
		 NULL /* nick */,
		 NULL /* blurb */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (g_object_class,
		PROP_DIALOG_PARENT,
		param_spec);
	param_spec = g_param_spec_object
		("mailbox" /* name */,
		 NULL /* nick */,
		 NULL /* blurb */,
		 MN_TYPE_MAILBOX /* object_type */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
	g_object_class_install_property (g_object_class,
		PROP_MAILBOX,
		param_spec);
    }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::set_property"
{
	MNMailboxPropertiesDialog *self G_GNUC_UNUSED;

	self = MN_MAILBOX_PROPERTIES_DIALOG (object);

	switch (property_id) {
	case PROP_DIALOG_PARENT:
		{
#line 64 "mn-mailbox-properties-dialog.gob"
self->_priv->dialog_parent = g_value_get_pointer (VAL);
#line 253 "mn-mailbox-properties-dialog.c"
		}
		break;
	case PROP_MAILBOX:
		{
#line 72 "mn-mailbox-properties-dialog.gob"

      GObject *object;

      if (selfp->mailbox)
	{
	  g_object_unref(selfp->mailbox);
	  selfp->mailbox = NULL;
	}

      object = g_value_dup_object(VAL);
      if (object)
	{
	  char *title;

	  selfp->mailbox = MN_MAILBOX(object);

	  title = g_strdup_printf(_("%s Properties"), selfp->mailbox->runtime_name);
	  gtk_window_set_title(GTK_WINDOW(self), title);
	  g_free(title);
	}
    
#line 280 "mn-mailbox-properties-dialog.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::get_property"
{
	MNMailboxPropertiesDialog *self G_GNUC_UNUSED;

	self = MN_MAILBOX_PROPERTIES_DIALOG (object);

	switch (property_id) {
	case PROP_DIALOG_PARENT:
		{
#line 64 "mn-mailbox-properties-dialog.gob"
g_value_set_pointer (VAL, self->_priv->dialog_parent);
#line 311 "mn-mailbox-properties-dialog.c"
		}
		break;
	case PROP_MAILBOX:
		{
#line 94 "mn-mailbox-properties-dialog.gob"

      g_value_set_object(VAL, selfp->mailbox);
    
#line 320 "mn-mailbox-properties-dialog.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__



#line 94 "mn-mailbox-properties-dialog.gob"
MNMailbox * 
mn_mailbox_properties_dialog_get_mailbox (MNMailboxPropertiesDialog * self)
#line 340 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::get_mailbox"
{
#line 67 "mn-mailbox-properties-dialog.gob"
		MNMailbox* val; g_object_get (G_OBJECT (self), "mailbox", &val, NULL); return val;
}}
#line 347 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 72 "mn-mailbox-properties-dialog.gob"
void 
mn_mailbox_properties_dialog_set_mailbox (MNMailboxPropertiesDialog * self, MNMailbox * val)
#line 353 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::set_mailbox"
{
#line 67 "mn-mailbox-properties-dialog.gob"
		g_object_set (G_OBJECT (self), "mailbox", val, NULL);
}}
#line 360 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 115 "mn-mailbox-properties-dialog.gob"
static GObject * 
___3_mn_mailbox_properties_dialog_constructor (GType type G_GNUC_UNUSED, unsigned int n_construct_properties, GObjectConstructParam * construct_params)
#line 366 "mn-mailbox-properties-dialog.c"
#define PARENT_HANDLER(___type,___n_construct_properties,___construct_params) \
	((G_OBJECT_CLASS(parent_class)->constructor)? \
		(* G_OBJECT_CLASS(parent_class)->constructor)(___type,___n_construct_properties,___construct_params): \
		((GObject * )0))
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::constructor"
{
#line 117 "mn-mailbox-properties-dialog.gob"
	
    GObject *object;
    Self *self;
    GtkCellRenderer *renderer;
    MNMailboxProperties *properties;

    object = PARENT_HANDLER(type, n_construct_properties, construct_params);
    self = SELF(object);

    mn_container_create_interface(GTK_CONTAINER(self),
				  MN_INTERFACE_FILE("mailbox-properties-dialog.glade"),
				  "vbox",
				  "mn_mailbox_properties_dialog_",
				  "mailbox_type_label", &selfp->mailbox_type_label,
				  "mailbox_type_combo", &selfp->mailbox_type_combo,
				  "mailbox_name_label", &selfp->mailbox_name_label,
				  "mailbox_name_entry", &selfp->mailbox_name_entry,
				  "mailbox_name_default_button", &selfp->mailbox_name_default_button,
				  "type_section_label", &selfp->type_section_label,
				  "properties_event_box", &selfp->properties_event_box,
				  NULL);

    gtk_window_set_resizable(GTK_WINDOW(self), FALSE);

    if (selfp->dialog_parent)
      gtk_window_set_transient_for(GTK_WINDOW(self), selfp->dialog_parent);

    /* finish the type combo box */

    selfp->store = gtk_list_store_new(N_COLUMNS,
				      GTK_TYPE_WIDGET,
				      G_TYPE_STRING,
				      G_TYPE_STRING);

    self_add_type(self, MN_TYPE_AUTODETECT_MAILBOX_PROPERTIES);
#if defined(WITH_MBOX) || defined(WITH_MH) || defined(WITH_MAILDIR) || defined(WITH_SYLPHEED)
    self_add_type(self, MN_TYPE_SYSTEM_VFS_MAILBOX_PROPERTIES);
#endif
#ifdef WITH_POP3
    self_add_type(self, MN_TYPE_POP3_MAILBOX_PROPERTIES);
#endif
#ifdef WITH_IMAP
    self_add_type(self, MN_TYPE_IMAP_MAILBOX_PROPERTIES);
#endif
#ifdef WITH_GMAIL
    self_add_type(self, MN_TYPE_GMAIL_MAILBOX_PROPERTIES);
#endif
#ifdef WITH_EVOLUTION
    self_add_type(self, MN_TYPE_EVOLUTION_MAILBOX_PROPERTIES);
#endif

    renderer = gtk_cell_renderer_pixbuf_new();
    g_object_set(renderer, "stock-size", GTK_ICON_SIZE_MENU, NULL);
    gtk_cell_layout_pack_start(GTK_CELL_LAYOUT(selfp->mailbox_type_combo), renderer, FALSE);;
    gtk_cell_layout_set_attributes(GTK_CELL_LAYOUT(selfp->mailbox_type_combo), renderer,
				   "stock-id", COLUMN_STOCK_ID,
				   NULL);

    renderer = gtk_cell_renderer_text_new();
    g_object_set(renderer, "xpad", 6, NULL);
    gtk_cell_layout_pack_start(GTK_CELL_LAYOUT(selfp->mailbox_type_combo), renderer, TRUE);
    gtk_cell_layout_set_attributes(GTK_CELL_LAYOUT(selfp->mailbox_type_combo), renderer,
				   "markup", COLUMN_LABEL,
				   NULL);

    gtk_combo_box_set_model(GTK_COMBO_BOX(selfp->mailbox_type_combo), GTK_TREE_MODEL(selfp->store));

    /* setup the dialog depending on the mode (edit or add) */

    gtk_dialog_add_button(GTK_DIALOG(self), GTK_STOCK_HELP, GTK_RESPONSE_HELP);
    if (selfp->mailbox)
      {
	selfp->apply_button = gtk_dialog_add_button(GTK_DIALOG(self), GTK_STOCK_APPLY, GTK_RESPONSE_APPLY);
	gtk_dialog_add_button(GTK_DIALOG(self), GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL);
	selfp->accept_button = gtk_dialog_add_button(GTK_DIALOG(self), GTK_STOCK_OK, GTK_RESPONSE_OK);
	
	properties = self_get_properties_by_type(self, MN_MAILBOX_GET_CLASS(selfp->mailbox)->type);
      }
    else
      {
	gtk_dialog_add_button(GTK_DIALOG(self), GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL);
	selfp->accept_button = gtk_dialog_add_button(GTK_DIALOG(self), GTK_STOCK_ADD, GTK_RESPONSE_ACCEPT);

	if (! selected_type)
	  selected_type = MN_TYPE_AUTODETECT_MAILBOX_PROPERTIES;

	properties = self_get_properties_by_g_type(self, selected_type);

	gtk_window_set_title(GTK_WINDOW(self), _("Add a Mailbox"));
      }

    self_set_active_properties(self, properties);

    if (selfp->mailbox)
      {
	mn_mailbox_properties_set_mailbox(properties, selfp->mailbox);
	if (selfp->mailbox->name)
	  gtk_entry_set_text(GTK_ENTRY(selfp->mailbox_name_entry), selfp->mailbox->name);
      }

    g_object_unref(properties);

    gtk_widget_grab_default(selfp->accept_button);

    return object;
  }}
#line 481 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 224 "mn-mailbox-properties-dialog.gob"
static void 
mn_mailbox_properties_dialog_add_type (MNMailboxPropertiesDialog * self, GType type)
#line 488 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::add_type"
#line 224 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (self != NULL);
#line 224 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (MN_IS_MAILBOX_PROPERTIES_DIALOG (self));
#line 224 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (type != 0);
#line 497 "mn-mailbox-properties-dialog.c"
{
#line 226 "mn-mailbox-properties-dialog.gob"
	
    MNMailboxProperties *properties;
    MNMailboxPropertiesClass *p_class;
    GtkTreeIter iter;
    GSList *l;

    properties = g_object_new(type, NULL);
    mn_gtk_object_ref_and_sink(GTK_OBJECT(properties));

    p_class = MN_MAILBOX_PROPERTIES_GET_CLASS(properties);

    gtk_list_store_append(selfp->store, &iter);
    gtk_list_store_set(selfp->store, &iter,
		       COLUMN_PROPERTIES, properties,
		       COLUMN_STOCK_ID, p_class->stock_id,
		       COLUMN_LABEL, p_class->combo_label,
		       -1);

    gtk_widget_show(GTK_WIDGET(properties));

    g_object_connect(properties,
		     "swapped-signal::notify::complete", self_update_complete, self,
		     "swapped-signal::notify::default-name", self_update_default_name, self,
		     NULL);

    MN_LIST_FOREACH(l, properties->entries)
      g_signal_connect_swapped(l->data, "activate", G_CALLBACK(self_entry_activate_h), self);

    g_object_unref(properties);	/* now it belongs to the store */
  }}
#line 530 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 257 "mn-mailbox-properties-dialog.gob"
static void 
mn_mailbox_properties_dialog_set_active_properties (MNMailboxPropertiesDialog * self, MNMailboxProperties * properties)
#line 536 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::set_active_properties"
#line 257 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (self != NULL);
#line 257 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (MN_IS_MAILBOX_PROPERTIES_DIALOG (self));
#line 257 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (properties != NULL);
#line 257 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (MN_IS_MAILBOX_PROPERTIES (properties));
#line 547 "mn-mailbox-properties-dialog.c"
{
#line 260 "mn-mailbox-properties-dialog.gob"
	
    gboolean valid;
    GtkTreeIter iter;

    valid = gtk_tree_model_get_iter_first(GTK_TREE_MODEL(selfp->store), &iter);
    while (valid)
      {
	MNMailboxProperties *these_properties;

	gtk_tree_model_get(GTK_TREE_MODEL(selfp->store), &iter, COLUMN_PROPERTIES, &these_properties, -1);
	g_object_unref(these_properties);

	if (these_properties == properties)
	  {
	    gtk_combo_box_set_active_iter(GTK_COMBO_BOX(selfp->mailbox_type_combo), &iter);
	    break;
	  }

	valid = gtk_tree_model_iter_next(GTK_TREE_MODEL(selfp->store), &iter);
      }
  }}
#line 571 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 282 "mn-mailbox-properties-dialog.gob"
static MNMailboxProperties * 
mn_mailbox_properties_dialog_get_active_properties (MNMailboxPropertiesDialog * self)
#line 577 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::get_active_properties"
#line 282 "mn-mailbox-properties-dialog.gob"
	g_return_val_if_fail (self != NULL, (MNMailboxProperties * )0);
#line 282 "mn-mailbox-properties-dialog.gob"
	g_return_val_if_fail (MN_IS_MAILBOX_PROPERTIES_DIALOG (self), (MNMailboxProperties * )0);
#line 584 "mn-mailbox-properties-dialog.c"
{
#line 284 "mn-mailbox-properties-dialog.gob"
	
    GtkTreeIter iter;
    MNMailboxProperties *properties = NULL;

    if (gtk_combo_box_get_active_iter(GTK_COMBO_BOX(selfp->mailbox_type_combo), &iter))
      gtk_tree_model_get(GTK_TREE_MODEL(selfp->store), &iter, COLUMN_PROPERTIES, &properties, -1);

    return properties;
  }}
#line 596 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 294 "mn-mailbox-properties-dialog.gob"
static MNMailboxProperties * 
mn_mailbox_properties_dialog_get_properties_by_type (MNMailboxPropertiesDialog * self, const char * type)
#line 602 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::get_properties_by_type"
#line 294 "mn-mailbox-properties-dialog.gob"
	g_return_val_if_fail (self != NULL, (MNMailboxProperties * )0);
#line 294 "mn-mailbox-properties-dialog.gob"
	g_return_val_if_fail (MN_IS_MAILBOX_PROPERTIES_DIALOG (self), (MNMailboxProperties * )0);
#line 294 "mn-mailbox-properties-dialog.gob"
	g_return_val_if_fail (type != NULL, (MNMailboxProperties * )0);
#line 611 "mn-mailbox-properties-dialog.c"
{
#line 296 "mn-mailbox-properties-dialog.gob"
	
    gboolean valid;
    GtkTreeIter iter;

    valid = gtk_tree_model_get_iter_first(GTK_TREE_MODEL(selfp->store), &iter);
    while (valid)
      {
	MNMailboxProperties *properties;
	MNMailboxPropertiesClass *class;

	gtk_tree_model_get(GTK_TREE_MODEL(selfp->store), &iter, COLUMN_PROPERTIES, &properties, -1);
	
	class = MN_MAILBOX_PROPERTIES_GET_CLASS(properties);

	if (class->type && ! strcmp(class->type, type))
	  return properties;

	g_object_unref(properties);

	valid = gtk_tree_model_iter_next(GTK_TREE_MODEL(selfp->store), &iter);
      }
    
    return NULL;
  }}
#line 638 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 321 "mn-mailbox-properties-dialog.gob"
static MNMailboxProperties * 
mn_mailbox_properties_dialog_get_properties_by_g_type (MNMailboxPropertiesDialog * self, GType type)
#line 644 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::get_properties_by_g_type"
#line 321 "mn-mailbox-properties-dialog.gob"
	g_return_val_if_fail (self != NULL, (MNMailboxProperties * )0);
#line 321 "mn-mailbox-properties-dialog.gob"
	g_return_val_if_fail (MN_IS_MAILBOX_PROPERTIES_DIALOG (self), (MNMailboxProperties * )0);
#line 321 "mn-mailbox-properties-dialog.gob"
	g_return_val_if_fail (type != 0, (MNMailboxProperties * )0);
#line 653 "mn-mailbox-properties-dialog.c"
{
#line 323 "mn-mailbox-properties-dialog.gob"
	
    gboolean valid;
    GtkTreeIter iter;

    valid = gtk_tree_model_get_iter_first(GTK_TREE_MODEL(selfp->store), &iter);
    while (valid)
      {
	MNMailboxProperties *properties;

	gtk_tree_model_get(GTK_TREE_MODEL(selfp->store), &iter, COLUMN_PROPERTIES, &properties, -1);

	if (G_TYPE_CHECK_INSTANCE_TYPE(properties, type))
	  return properties;

	g_object_unref(properties);

	valid = gtk_tree_model_iter_next(GTK_TREE_MODEL(selfp->store), &iter);
      }

    return NULL;
  }}
#line 677 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 345 "mn-mailbox-properties-dialog.gob"
MNMailbox * 
mn_mailbox_properties_dialog_get_current_mailbox (MNMailboxPropertiesDialog * self)
#line 683 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::get_current_mailbox"
#line 345 "mn-mailbox-properties-dialog.gob"
	g_return_val_if_fail (self != NULL, (MNMailbox * )0);
#line 345 "mn-mailbox-properties-dialog.gob"
	g_return_val_if_fail (MN_IS_MAILBOX_PROPERTIES_DIALOG (self), (MNMailbox * )0);
#line 690 "mn-mailbox-properties-dialog.c"
{
#line 347 "mn-mailbox-properties-dialog.gob"
	
    MNMailboxProperties *properties;
    MNMailbox *mailbox;

    properties = self_get_active_properties(self);
    mailbox = mn_mailbox_properties_get_mailbox(properties);
    g_object_unref(properties);

    if (selfp->custom_name)
      g_object_set(G_OBJECT(mailbox), "name", gtk_entry_get_text(GTK_ENTRY(selfp->mailbox_name_entry)), NULL);

    return mailbox;
  }}
#line 706 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 361 "mn-mailbox-properties-dialog.gob"
void 
mn_mailbox_properties_dialog_apply (MNMailboxPropertiesDialog * self)
#line 712 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::apply"
#line 361 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (self != NULL);
#line 361 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (MN_IS_MAILBOX_PROPERTIES_DIALOG (self));
#line 719 "mn-mailbox-properties-dialog.c"
{
#line 363 "mn-mailbox-properties-dialog.gob"
	
    MNMailbox *new_mailbox;

    new_mailbox = self_get_current_mailbox(self);
    g_return_if_fail(MN_IS_MAILBOX(new_mailbox));

    mn_mailbox_seal(new_mailbox);

    mn_mailboxes_queue_remove(mn_shell->mailboxes, selfp->mailbox);
    mn_mailboxes_queue_add(mn_shell->mailboxes, new_mailbox);

    self_set_mailbox(self, new_mailbox);
    g_object_unref(new_mailbox);
  }}
#line 736 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 378 "mn-mailbox-properties-dialog.gob"
static void 
mn_mailbox_properties_dialog_update_complete (MNMailboxPropertiesDialog * self)
#line 742 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::update_complete"
#line 378 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (self != NULL);
#line 378 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (MN_IS_MAILBOX_PROPERTIES_DIALOG (self));
#line 749 "mn-mailbox-properties-dialog.c"
{
#line 380 "mn-mailbox-properties-dialog.gob"
	
    MNMailboxProperties *properties;

    properties = self_get_active_properties(self);
    if (properties)
      {
	gboolean complete;

	g_object_get(G_OBJECT(properties), "complete", &complete, NULL);
	g_object_unref(properties);

	gtk_widget_set_sensitive(selfp->mailbox_name_entry, complete);
	gtk_widget_set_sensitive(selfp->mailbox_name_default_button, complete && selfp->custom_name);
	if (selfp->apply_button)
	  gtk_widget_set_sensitive(selfp->apply_button, complete);
	gtk_widget_set_sensitive(selfp->accept_button, complete);
      }
  }}
#line 770 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 399 "mn-mailbox-properties-dialog.gob"
static void 
mn_mailbox_properties_dialog_update_default_name (MNMailboxPropertiesDialog * self)
#line 776 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::update_default_name"
#line 399 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (self != NULL);
#line 399 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (MN_IS_MAILBOX_PROPERTIES_DIALOG (self));
#line 783 "mn-mailbox-properties-dialog.c"
{
#line 401 "mn-mailbox-properties-dialog.gob"
	
    MNMailboxProperties *properties;

    properties = self_get_active_properties(self);
    if (properties)
      {
	gboolean complete;
	const char *default_name;

	g_free(selfp->default_name);

	g_object_get(G_OBJECT(properties),
		     "complete", &complete,
		     "default-name", &selfp->default_name,
		     NULL);
	g_object_unref(properties);

	default_name = complete ? selfp->default_name : NULL;
      
	gtk_entry_set_text(GTK_ENTRY(selfp->mailbox_name_entry), default_name ? default_name : "");
	gtk_widget_set_sensitive(selfp->mailbox_name_default_button, selfp->custom_name = FALSE);
      }
  }}
#line 809 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 425 "mn-mailbox-properties-dialog.gob"
GtkWidget * 
mn_mailbox_properties_dialog_new (GtkWindow * parent, MNMailbox * mailbox)
#line 815 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::new"
{
#line 427 "mn-mailbox-properties-dialog.gob"
	
    return GTK_WIDGET(GET_NEW_VARG(MN_MAILBOX_PROPERTIES_DIALOG_PROP_DIALOG_PARENT(parent),
				   MN_MAILBOX_PROPERTIES_DIALOG_PROP_MAILBOX(mailbox),
				   NULL));
  }}
#line 825 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 435 "mn-mailbox-properties-dialog.gob"
void 
mn_mailbox_properties_dialog_type_changed_h (MNMailboxPropertiesDialog * self, GtkComboBox * combobox)
#line 831 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::type_changed_h"
#line 435 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (self != NULL);
#line 435 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (MN_IS_MAILBOX_PROPERTIES_DIALOG (self));
#line 838 "mn-mailbox-properties-dialog.c"
{
#line 437 "mn-mailbox-properties-dialog.gob"
	
    MNMailboxProperties *properties;
    MNMailboxPropertiesClass *class;
    char *markup;

    properties = (MNMailboxProperties *) GTK_BIN(selfp->properties_event_box)->child;
    if (properties)
      {
	gtk_size_group_remove_widget(properties->label_size_group, selfp->mailbox_type_label);
	gtk_size_group_remove_widget(properties->label_size_group, selfp->mailbox_name_label);
	gtk_size_group_remove_widget(properties->entry_button_size_group, selfp->mailbox_name_default_button);
	gtk_container_remove(GTK_CONTAINER(selfp->properties_event_box), GTK_WIDGET(properties));
      }
  
    properties = self_get_active_properties(self);
    gtk_container_add(GTK_CONTAINER(selfp->properties_event_box), GTK_WIDGET(properties));
    gtk_size_group_add_widget(properties->label_size_group, selfp->mailbox_type_label);
    gtk_size_group_add_widget(properties->label_size_group, selfp->mailbox_name_label);
    gtk_size_group_add_widget(properties->entry_button_size_group, selfp->mailbox_name_default_button);
    
    class = MN_MAILBOX_PROPERTIES_GET_CLASS(properties);
    
    markup = g_markup_printf_escaped("<span weight=\"bold\">%s</span>", class->section_label ? class->section_label : class->combo_label);
    gtk_label_set_markup(GTK_LABEL(selfp->type_section_label), markup);
    g_free(markup);

    if (! selfp->mailbox)	/* mode is add */
      selected_type = G_TYPE_FROM_INSTANCE(properties);

    self_update_complete(self);
    self_update_default_name(self);

    g_object_unref(properties);
  }}
#line 875 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 472 "mn-mailbox-properties-dialog.gob"
void 
mn_mailbox_properties_dialog_name_changed_h (MNMailboxPropertiesDialog * self, GtkEditable * editable)
#line 881 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::name_changed_h"
#line 472 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (self != NULL);
#line 472 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (MN_IS_MAILBOX_PROPERTIES_DIALOG (self));
#line 888 "mn-mailbox-properties-dialog.c"
{
#line 474 "mn-mailbox-properties-dialog.gob"
	
    const char *name;

    name = gtk_entry_get_text(GTK_ENTRY(selfp->mailbox_name_entry));
    selfp->custom_name = mn_utf8_strcmp(name, selfp->default_name ? selfp->default_name : "") != 0;

    gtk_widget_set_sensitive(selfp->mailbox_name_default_button, selfp->custom_name);
  }}
#line 899 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 483 "mn-mailbox-properties-dialog.gob"
void 
mn_mailbox_properties_dialog_name_default_button_clicked_h (MNMailboxPropertiesDialog * self, GtkButton * button)
#line 905 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::name_default_button_clicked_h"
#line 483 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (self != NULL);
#line 483 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (MN_IS_MAILBOX_PROPERTIES_DIALOG (self));
#line 912 "mn-mailbox-properties-dialog.c"
{
#line 485 "mn-mailbox-properties-dialog.gob"
	
    self_update_default_name(self);
  }}
#line 918 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__

#line 489 "mn-mailbox-properties-dialog.gob"
void 
mn_mailbox_properties_dialog_entry_activate_h (MNMailboxPropertiesDialog * self, GtkEntry * entry)
#line 924 "mn-mailbox-properties-dialog.c"
{
#define __GOB_FUNCTION__ "MN:Mailbox:Properties:Dialog::entry_activate_h"
#line 489 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (self != NULL);
#line 489 "mn-mailbox-properties-dialog.gob"
	g_return_if_fail (MN_IS_MAILBOX_PROPERTIES_DIALOG (self));
#line 931 "mn-mailbox-properties-dialog.c"
{
#line 491 "mn-mailbox-properties-dialog.gob"
	
    if (GTK_WIDGET_IS_SENSITIVE(GTK_WINDOW(self)->default_widget))
      gtk_window_activate_default(GTK_WINDOW(self));
    else
      {
	MNMailboxProperties *properties;
	GtkWidget *next = GTK_WIDGET(entry);

	properties = self_get_active_properties(self);
	g_return_if_fail(properties != NULL);

	do
	  {
	    GSList *elem;

	    if (next == selfp->mailbox_name_entry)
	      elem = properties->entries;
	    else
	      {
		elem = g_slist_find(properties->entries, next);
		g_return_if_fail(elem != NULL);

		elem = elem->next;
	      }

	    next = elem ? elem->data : selfp->mailbox_name_entry;
	    if (next == GTK_WIDGET(entry))
	      next = NULL;
	  }
	while (next && ! (GTK_WIDGET_MAPPED(next)
			  && GTK_WIDGET_VISIBLE(next)
			  && GTK_WIDGET_SENSITIVE(next)));

	if (next)
	  gtk_widget_grab_focus(next);
      }
  }}
#line 971 "mn-mailbox-properties-dialog.c"
#undef __GOB_FUNCTION__
