/* Generated by GOB (v2.0.14)   (do not edit directly) */

#ifndef __MN_MAIL_ICON_PRIVATE_H__
#define __MN_MAIL_ICON_PRIVATE_H__

#include "mn-mail-icon.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#line 28 "mn-mail-icon.gob"

#include "mn-tooltips.h"

#line 18 "mn-mail-icon-private.h"
struct _MNMailIconPrivate {
#line 42 "mn-mail-icon.gob"
	MNTooltips * tooltips;
#line 43 "mn-mail-icon.gob"
	GtkWidget * event_box;
#line 46 "mn-mail-icon.gob"
	GtkWidget * menu;
#line 26 "mn-mail-icon-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
