/* Generated by GOB (v2.0.11)   (do not edit directly) */

#ifndef __MN_MBOX_MAILBOX_PRIVATE_H__
#define __MN_MBOX_MAILBOX_PRIVATE_H__

#include "mn-mbox-mailbox.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#line 24 "mn-mbox-mailbox.gob"

#include <libgnomevfs/gnome-vfs.h>

#line 18 "mn-mbox-mailbox-private.h"
struct _MNmboxMailboxPrivate {
#line 41 "mn-mbox-mailbox.gob"
	time_t last_mtime;
#line 22 "mn-mbox-mailbox-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
