/* Generated by GOB (v2.0.14)   (do not edit directly) */

#ifndef __MN_SYLPHEED_MAILBOX_BACKEND_PRIVATE_H__
#define __MN_SYLPHEED_MAILBOX_BACKEND_PRIVATE_H__

#include "mn-sylpheed-mailbox-backend.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#line 26 "mn-sylpheed-mailbox-backend.gob"

#include "mn-locked-callback.h"

/* taken from procmsg.h in the Sylpheed sources */
#define SYLPHEED_MSG_NEW	(1U << 0)
#define SYLPHEED_MSG_UNREAD	(1U << 1)

/* taken from defs.h in the Sylpheed sources */
#define SYLPHEED_MARK_FILE	".sylpheed_mark"

typedef struct
{
  int		num;
  guint32	flags;
} MarkEntry;

typedef struct
{
  char		*data;
  gsize		data_size;
  GHashTable	*table;
} Marks;

#line 38 "mn-sylpheed-mailbox-backend-private.h"
Marks * 	mn_sylpheed_mailbox_backend_marks_new	(GnomeVFSURI * mailbox_uri, GError ** err);
gboolean 	mn_sylpheed_mailbox_backend_marks_write	(GnomeVFSURI * mailbox_uri, Marks * marks, GError ** err);
void 	mn_sylpheed_mailbox_backend_marks_free	(Marks * marks);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
