/* Generated by GOB (v2.0.14)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>


#include <gtk/gtk.h>
#include "mn-mailboxes.h"
#include "mn-mailbox-properties-dialog.h"
#include "mn-mail-icon.h"
#include "mn-popups.h"

#ifndef __MN_SHELL_H__
#define __MN_SHELL_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


typedef enum {
	MN_SHELL_TOOLTIP_MAIL_SUMMARY_STANDARD,
	MN_SHELL_TOOLTIP_MAIL_SUMMARY_COMPACT,
	MN_SHELL_TOOLTIP_MAIL_SUMMARY_NONE
} MNShellTooltipMailSummary;
#define MN_TYPE_SHELL_TOOLTIP_MAIL_SUMMARY mn_shell_tooltip_mail_summary_get_type()
GType mn_shell_tooltip_mail_summary_get_type (void);


/*
 * Type checking and casting macros
 */
#define MN_TYPE_SHELL	(mn_shell_get_type())
#define MN_SHELL(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), mn_shell_get_type(), MNShell)
#define MN_SHELL_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), mn_shell_get_type(), MNShell const)
#define MN_SHELL_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), mn_shell_get_type(), MNShellClass)
#define MN_IS_SHELL(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), mn_shell_get_type ())

#define MN_SHELL_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), mn_shell_get_type(), MNShellClass)

/* Private structure type */
typedef struct _MNShellPrivate MNShellPrivate;

/*
 * Main object structure
 */
#ifndef __TYPEDEF_MN_SHELL__
#define __TYPEDEF_MN_SHELL__
typedef struct _MNShell MNShell;
#endif
struct _MNShell {
	GObject __parent__;
	/*< public >*/
	MNMailboxes * mailboxes;
	MNMailIcon * icon;
	MNPopups * popups;
	/*< private >*/
	MNShellPrivate *_priv;
};

/*
 * Class definition
 */
typedef struct _MNShellClass MNShellClass;
struct _MNShellClass {
	GObjectClass __parent__;
};


/*
 * Public methods
 */
GType	mn_shell_get_type	(void);
MNShell * 	mn_shell_new	(void);
void 	mn_shell_display_properties_dialog	(MNShell * self);
void 	mn_shell_display_about_dialog	(MNShell * self);
void 	mn_shell_add_mailbox_properties_dialog	(MNShell * self,
					MNMailboxPropertiesDialog * dialog);
MNMailboxPropertiesDialog * 	mn_shell_get_mailbox_properties_dialog	(MNShell * self,
					MNMailbox * mailbox);
char * 	mn_shell_get_summary	(MNShell * self);


extern MNShell *mn_shell;


typedef enum {
	MN_ACTION_DISPLAY_PROPERTIES_DIALOG,
	MN_ACTION_LAUNCH_MAIL_READER,
	MN_ACTION_OPEN_LATEST_MESSAGE,
	MN_ACTION_UPDATE_MAIL_STATUS
} MNAction;
#define MN_TYPE_ACTION mn_action_get_type()
GType mn_action_get_type (void);


typedef enum {
	MN_EXPIRATION_ENABLED_DEFAULT,
	MN_EXPIRATION_ENABLED_FALSE,
	MN_EXPIRATION_ENABLED_TRUE
} MNExpirationEnabled;
#define MN_TYPE_EXPIRATION_ENABLED mn_expiration_enabled_get_type()
GType mn_expiration_enabled_get_type (void);


typedef enum {
	MN_POPUP_POSITION_ATTACHED,
	MN_POPUP_POSITION_FREE
} MNPopupPosition;
#define MN_TYPE_POPUP_POSITION mn_popup_position_get_type()
GType mn_popup_position_get_type (void);


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
