/* Generated by GOB (v2.0.11)   (do not edit directly) */

#ifndef __MN_UNSUPPORTED_MAILBOX_PRIVATE_H__
#define __MN_UNSUPPORTED_MAILBOX_PRIVATE_H__

#include "mn-unsupported-mailbox.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _MNUnsupportedMailboxPrivate {
#line 32 "mn-unsupported-mailbox.gob"
	char * reason;
#line 16 "mn-unsupported-mailbox-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
